name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set env
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build JVM Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/jvm/Dockerfile'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-jvm
    - name: Build JVM Alpine Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/jvm/Dockerfile.alpine'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-jvm-alpine
    - name: Build BPF Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/bpf/Dockerfile'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-bpf
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.38